return function(T, root, load)
  local Placement = load("src/placement.lua")

  T.test("placement layers keep independent terrain through copy move and delete", function()
    local stack = Placement.newStack()
    T.equal(#stack.layers,1)
    T.equal(stack.selected,1)
    Placement.set(stack.layers[1].ground,0,0,1)
    local copied = Placement.copyLayer(stack,1)
    T.equal(stack.selected,2)
    T.equal(Placement.get(copied.ground,0,0),1)
    Placement.set(copied.ground,0,0,0)
    T.equal(Placement.get(stack.layers[1].ground,0,0),1)
    Placement.moveLayer(stack,2,1)
    T.equal(stack.layers[1],copied)
    T.equal(stack.selected,1)
    Placement.deleteLayer(stack,1)
    T.equal(Placement.get(stack.layers[1].ground,0,0),1)
    T.equal(stack.selected,1)
  end)

  T.test("placement layer selection can be cleared and height follows order", function()
    local stack = Placement.newStack()
    Placement.addLayer(stack)
    T.equal(Placement.layerOffset(1,12,2),0)
    T.equal(Placement.layerOffset(2,12,2),-24)
    T.equal(Placement.layerOffset(3,12,0.5),-12)
    T.equal(Placement.layerOffset(2,0,2),0)
    Placement.selectLayer(stack,2)
    T.equal(stack.selected,nil)
    Placement.selectLayer(stack,1)
    T.equal(stack.selected,1)
    Placement.deleteLayer(stack,1)
    Placement.deleteLayer(stack,1)
    T.equal(#stack.layers,0)
    T.equal(stack.selected,nil)
    Placement.addLayer(stack)
    T.equal(stack.selected,1)
  end)

  T.test("copy inserts directly above its source layer", function()
    local stack=Placement.newStack()
    local top=Placement.addLayer(stack)
    local copy=Placement.copyLayer(stack,1)
    T.equal(stack.layers[2],copy)
    T.equal(stack.layers[3],top)
    T.equal(stack.selected,2)
  end)
end
