"""Encode the reference masks as column runs for side_copy.lua.

Run from the repository root after changing an assets/*_mask.png file.
Requires Pillow. The generated Lua module does not read image files at runtime.
"""

from pathlib import Path
from PIL import Image


ROOT = Path(__file__).resolve().parent.parent
MODES = ("transparent", "opaque", "interlaced")
PALETTE = (
    (82, 75, 36, 255),
    (75, 105, 47, 255),
    (106, 190, 48, 255),
    (55, 148, 110, 255),
    (91, 110, 225, 255),
    (99, 155, 255, 255),
    (215, 123, 186, 255),
    (118, 66, 138, 255),
)


def encode_tile(image, tile):
    data = bytearray()
    origin_x, origin_y = tile % 4 * 64, tile // 4 * 64
    for x in range(64):
        runs = []
        previous, start = None, 0
        for y in range(65):
            color = image.getpixel((origin_x + x, origin_y + y)) if y < 64 else None
            if color is not None and color[3] == 0:
                color = None
            if color != previous:
                if previous is not None:
                    runs.append((start, y - start, PALETTE.index(previous) + 1))
                previous, start = color, y
        data.append(len(runs))
        for start, length, color_id in runs:
            data.extend((start, length, color_id))
    return data.hex()


def main():
    lines = ["-- Generated by scripts/build_side_copy_data.py; do not edit by hand.",
             "return {", "  colors={"]
    for color in PALETTE:
        lines.append("    {%d,%d,%d,%d}," % color)
    lines.append("  },")
    for mode in MODES:
        image = Image.open(ROOT / "assets" / f"{mode}_mask.png").convert("RGBA")
        if image.size != (256, 256):
            raise ValueError(f"{mode} reference must be 256x256")
        lines.append(f"  {mode}={{")
        for tile in range(16):
            encoded = encode_tile(image, tile)
            chunks = [encoded[i:i + 100] for i in range(0, len(encoded), 100)]
            lines.append("    " + " ..\n    ".join('"' + chunk + '"' for chunk in chunks) + ",")
        lines.append("  },")
    lines.append("}")
    (ROOT / "src" / "side_copy_data.lua").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
